PLUGIN_NAME=		caddy-plus
PLUGIN_VERSION=		2.0.2
PLUGIN_REVISION=	2
PLUGIN_DEPENDS=		caddy
PLUGIN_COMMENT=		Feature complete Reverse Proxy with Automatic HTTPS, Dynamic DNS and Layer4 Routing
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
