PLUGIN_NAME=		caddy-plus
PLUGIN_VERSION=		2.0.1
PLUGIN_COMMENT=		Feature complete Reverse Proxy with Automatic HTTPS, Dynamic DNS and Layer4 Routing
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
